version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          name: npm install
          command: npm ci
      - run:
          name: Add env
          command: |
            echo "VUE_APP_FIREBASE_API_KEY=$FIREBASE_API_KEY" > .env
            echo "VUE_APP_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN" >> .env
            echo "VUE_APP_FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL" >> .env
            echo "VUE_APP_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID" >> .env
            echo "VUE_APP_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET" >> .env
            echo "VUE_APP_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID" >> .env
            echo "VUE_APP_FIREBASE_APP_ID=$FIREBASE_APP_ID" >> .env
            echo "VUE_APP_API_BASE_URL=$API_BASE_URL" >> .env
            echo "VUE_APP_FIREBASE_STORAGE_DIR=$FIREBASE_STORAGE_DIR" >> .env
      - run:
          name: clean
          command: npm run clean
      - run:
          name: build
          command: npm run build
      - run:
          name: deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
